"""
email_service.py — Professional email delivery with resume attachments.

Sends generated resumes (PDF + DOCX) to users via SMTP.
Includes a clean HTML email template and retry logic.
"""

import logging
import os
import smtplib
import time
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import Config

logger = logging.getLogger(__name__)


def _build_email_html(name: str, domain: str, quality_grade: str = "B") -> str:
    """Build a professional HTML email body."""
    return f"""\
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background-color:#f0f4f8;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f0f4f8;padding:40px 0;">
<tr><td align="center">
<table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

  <!-- Header -->
  <tr>
    <td style="background:linear-gradient(135deg,#6366f1,#06b6d4);padding:32px 40px;text-align:center;">
      <h1 style="color:#ffffff;margin:0;font-size:28px;font-weight:800;letter-spacing:-0.5px;">
        ✨ Your Resume is Ready!
      </h1>
      <p style="color:rgba(255,255,255,0.85);margin:8px 0 0;font-size:15px;">
        Powered by ResumeAI — Domain-Aware Generation
      </p>
    </td>
  </tr>

  <!-- Body -->
  <tr>
    <td style="padding:36px 40px;">
      <p style="color:#1e293b;font-size:17px;margin:0 0 20px;line-height:1.6;">
        Hi <strong>{name}</strong>,
      </p>

      <p style="color:#475569;font-size:15px;margin:0 0 24px;line-height:1.7;">
        Great news! Our AI has analyzed your profile, classified your domain
        as <strong style="color:#6366f1;">{domain}</strong>, and generated
        a professional, ATS-optimized resume tailored to your field.
      </p>

      <!-- Stats Card -->
      <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border-radius:12px;border:1px solid #e2e8f0;margin:0 0 24px;">
        <tr>
          <td style="padding:20px 24px;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="text-align:center;padding:8px;">
                  <div style="color:#6366f1;font-size:24px;font-weight:800;">{domain}</div>
                  <div style="color:#94a3b8;font-size:12px;margin-top:4px;">DOMAIN</div>
                </td>
                <td style="text-align:center;padding:8px;border-left:1px solid #e2e8f0;">
                  <div style="color:#10b981;font-size:24px;font-weight:800;">{quality_grade}</div>
                  <div style="color:#94a3b8;font-size:12px;margin-top:4px;">QUALITY</div>
                </td>
                <td style="text-align:center;padding:8px;border-left:1px solid #e2e8f0;">
                  <div style="color:#06b6d4;font-size:24px;font-weight:800;">ATS ✓</div>
                  <div style="color:#94a3b8;font-size:12px;margin-top:4px;">OPTIMIZED</div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>

      <p style="color:#475569;font-size:15px;margin:0 0 8px;line-height:1.7;">
        📎 <strong>Attached files:</strong>
      </p>
      <ul style="color:#475569;font-size:14px;line-height:1.8;margin:0 0 24px;padding-left:20px;">
        <li><strong>resume.pdf</strong> — Ready to submit to job portals</li>
        <li><strong>resume.docx</strong> — Editable version for customization</li>
      </ul>

      <p style="color:#475569;font-size:14px;margin:0;line-height:1.7;padding:16px;background:#fefce8;border-radius:8px;border:1px solid #fde68a;">
        💡 <strong>Pro Tip:</strong> Review the generated resume, personalize any
        sections, and tailor it further for each specific job application.
      </p>
    </td>
  </tr>

  <!-- Footer -->
  <tr>
    <td style="background:#f8fafc;padding:20px 40px;text-align:center;border-top:1px solid #e2e8f0;">
      <p style="color:#94a3b8;font-size:12px;margin:0;line-height:1.6;">
        Generated by <strong>ResumeAI</strong> — AI-Powered Domain-Aware Resume Generator<br>
        Built with DistilBERT + Gemini AI
      </p>
    </td>
  </tr>

</table>
</td></tr>
</table>
</body>
</html>
"""


def send_resume_email(
    to_email: str,
    name: str,
    domain: str,
    pdf_path: str | None = None,
    docx_path: str | None = None,
    quality_grade: str = "B",
    max_retries: int = 2,
) -> dict:
    """
    Send the generated resume to the user's email.

    Args:
        to_email:      Recipient email address
        name:          Candidate name (for personalization)
        domain:        Classified domain
        pdf_path:      Absolute path to generated PDF file
        docx_path:     Absolute path to generated DOCX file
        quality_grade: Resume quality grade (A-D)
        max_retries:   Number of retry attempts

    Returns:
        dict with 'success' bool and 'message' string
    """
    if not Config.EMAIL_ENABLED:
        return {"success": False, "message": "Email not configured (SMTP credentials missing)"}

    if not to_email or not to_email.strip():
        return {"success": False, "message": "No recipient email provided"}

    for attempt in range(1, max_retries + 1):
        try:
            msg = MIMEMultipart("mixed")
            msg["From"] = f"{Config.EMAIL_FROM_NAME} <{Config.SMTP_USER}>"
            msg["To"] = to_email
            msg["Subject"] = f"✨ Your AI-Generated Resume is Ready — {name}"

            # HTML body
            html_body = _build_email_html(name, domain, quality_grade)
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            # Attach PDF
            if pdf_path and os.path.exists(pdf_path):
                with open(pdf_path, "rb") as f:
                    part = MIMEBase("application", "pdf")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename=resume_{name.replace(' ', '_')}.pdf",
                    )
                    msg.attach(part)

            # Attach DOCX
            if docx_path and os.path.exists(docx_path):
                with open(docx_path, "rb") as f:
                    part = MIMEBase(
                        "application",
                        "vnd.openxmlformats-officedocument.wordprocessingml.document",
                    )
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename=resume_{name.replace(' ', '_')}.docx",
                    )
                    msg.attach(part)

            # Send
            with smtplib.SMTP(Config.SMTP_HOST, Config.SMTP_PORT) as server:
                server.ehlo()
                server.starttls()
                server.ehlo()
                server.login(Config.SMTP_USER, Config.SMTP_PASSWORD)
                server.send_message(msg)

            logger.info(f"📧 Resume emailed successfully to {to_email}")
            return {"success": True, "message": f"Resume sent to {to_email}"}

        except Exception as exc:
            logger.error(f"Email attempt {attempt} failed: {exc}")
            if attempt == max_retries:
                return {"success": False, "message": f"Email delivery failed: {str(exc)}"}
            time.sleep(2 ** attempt)

    return {"success": False, "message": "Email delivery failed after all retries"}
